version: '3.3'

services:

  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users-service:
    container_name: users-service
    build:
      context: ../ezasdf-users
      dockerfile: Dockerfile-local
    volumes:
      - '../ezasdf-users:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=secret
      - FLASK_APP=ezasdf_users.py
    depends_on:
      - users-db
    links:
      - users-db

  web-service:
    container_name: web-service
    build:
      context: ../ezasdf-client
      dockerfile: Dockerfile-local
    volumes:
      - '../ezasdf-client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users-service
    links:
      - users-service

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
      - web-service
    links:
      - users-service
      - web-service

  swagger:
    container_name: swagger
    build:
      context: ../ezasdf-swagger
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/boheepark/ezasdf-swagger/master/swagger.json
    depends_on:
      - users-service
