version: '3.3'

services:

  users-db:
    container_name: users-db
    build:
      context: https://github.com/boheepark/store.git#master:services/users/project/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users-service:
    container_name: users-service
    build:
      context: https://github.com/boheepark/ezasdf-users.git
      dockerfile: Dockerfile
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_staging
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=ezasdf_users.py
    depends_on:
      - users-db
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 ezasdf_users:app

  web-service:
    container_name: web-service
    build:
      context: https://github.com/boheepark/ezasdf-client.git
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    depends_on:
      - users-service
    links:
      - users-service

  swagger:
    container_name: swagger
    build:
      context: https://github.com/boheepark/ezasdf-swagger.git
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/boheepark/ezasdf-swagger/master/swagger.json
    depends_on:
      - users-service

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
      - web-service
    links:
      - users-service
      - web-service
